kind: "EntandoCompositeApp"
apiVersion: "entando.org/v1"
metadata:
  name: "fornitori-composite-app"
entandoStatus:
  entandoDeploymentPhase: "requested"
spec:
  components:
    - kind: "EntandoApp"
      metadata:
        name: "fornitori-app"
      spec:
        dbms: postgresql
        replicas: 1
        standardServerImage: wildfly
        ingressPath: /entando-de-app
    - kind: "EntandoPlugin"
      metadata:
        name: "anagraficafornitori-plugin"
      spec:
#        image: postesviluppo.azurecr.io/portale-fornitori/anagrafica-fornitori:1.0.1
        image: entando/entando-avatar-plugin
        replicas: 1
        dbms: postgresql
        parameters: {}
        ingressPath: "/anagraficaFornitori"
        healthCheckPath: "/management/health"
        securityLevel: "strict"
        connectionConfigNames: []
        permissions: []
        roles:
          - name: anagraficaFornitori-admin
            code: anagraficaFornitori-admin
          - name: fornitore-admin
            code: "fornitore-admin"
    - kind: EntandoAppPluginLink
      metadata:
        name: anagrafica-fornitori-link
      spec:
        entandoAppNamespace: portale-fornitori
        entandoAppName: fornitori-app
        entandoPluginNamespace: portale-fornitori
        entandoPluginName: anagraficafornitori-plugin
