---
kind: ServiceAccount
apiVersion: v1
imagePullSecrets:
  - name: postesviluppo-azurecr-io
metadata:
  name: entando-plugin
---
kind: RoleBinding
apiVersion: authorization.openshift.io/v1
metadata:
  name: entando-editor-rolebinding
roleRef:
  name: entando-editor
subjects:
  - kind: ServiceAccount
    name: entando-plugin
    namespace: portale-fornitori
  - kind: ServiceAccount
    name: entando-operator
    namespace: entando-operator
---
kind: RoleBinding
apiVersion: authorization.openshift.io/v1
metadata:
  name: entando-operator-rolebinding
roleRef:
  name: edit
subjects:
  - kind: ServiceAccount
    name: entando-operator
    namespace: entando-operator
---
kind: "EntandoCompositeApp"
apiVersion: "entando.org/v1"
metadata:
  name: "fornitori-composite-app"
entandoStatus:
  entandoDeploymentPhase: "requested"
spec:
  components:
    - kind: "EntandoApp"
      metadata:
        name: "fornitori-app"
      spec:
        dbms: postgresql
        replicas: 1
        standardServerImage: wildfly
        ingressPath: /entando-de-app
    - kind: "EntandoPlugin"
      metadata:
        name: "anagraficafornitori-plugin"
      spec:
        image: postesviluppo.azurecr.io/portale-fornitori/anagrafica-fornitori:1.0.1
        replicas: 1
        dbms: postgresql
        parameters: {}
        ingressPath: "/anagraficaFornitori"
        healthCheckPath: "/management/health"
        securityLevel: "strict"
        connectionConfigNames: []
        permissions: []
        roles:
          - name: anagraficaFornitori-admin
            code: anagraficaFornitori-admin
          - name: fornitore-admin
            code: "fornitore-admin"
    - kind: EntandoAppPluginLink
      metadata:
        name: anagrafica-fornitori-link
      spec:
        entandoAppName:
        entandoAppNamespace:
        entandoPluginNamespace:
        entandoPluginName:
