---
kind: ServiceAccount
apiVersion: v1
imagePullSecrets:
  - name: postesviluppo-azurecr-io
metadata:
  name: entando-plugin
---
kind: RoleBinding
apiVersion: authorization.openshift.io/v1
metadata:
  name: entando-editor-rolebinding
roleRef:
  name: entando-editor
subjects:
  - kind: ServiceAccount
    name: entando-plugin
    namespace: portale-fornitori
  - kind: ServiceAccount
    name: entando-operator
    namespace: entando-operator
---
kind: RoleBinding
apiVersion: authorization.openshift.io/v1
metadata:
  name: entando-operator-rolebinding
roleRef:
  name: edit
subjects:
  - kind: ServiceAccount
    name: entando-operator
    namespace: entando-operator
