{{- if and .Values.externalDatabase (ne .Values.app.dbms "none") }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.app.name }}-db-admin-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  username:  "{{ .Values.externalDatabase.username }}"
  password: "{{ .Values.externalDatabase.password }}"
{{- end }}
